src-include defaults feeds.conf.default
src-git immortalwrt_packages https://github.com/immortalwrt/packages.git;openwrt-24.10
src-git immortalwrt_luci https://github.com/immortalwrt/luci.git;openwrt-24.10