# iStoreOS 第三方插件配置
# 每行一个包，格式：CONFIG_PACKAGE_包名=y
# 此文件在 diy-part2.d/istoreos.sh 中自动追加到 .config
src-git kcptun https://github.com/kuoruan/openwrt-kcptun.git
src-git airohanpu https://github.com/rchen14b/luci-app-airoha-npu.git;main
src-git kenzok8 https://github.com/kenzok8/openwrt-clashoo.git;main
src-git sirpdboy https://github.com/sirpdboy/luci-app-poweroffdevice.git;master
src-git wukongdaily https://github.com/wukongdaily/luci-app-run.git;master
src-git nikki https://github.com/nikkinikki-org/OpenWrt-nikki.git;main
